# adapted from https://github.com/marketplace/actions/flake8-action
name: Flake8

on: [pull_request, push]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.9
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 --ignore N802,N806 `find . -name *.py | grep -v setup.py | grep -v /doc/`
      - name: Store flake8 results
        if: ${{ always() }}
        run: flake8 --ignore N802,N806 `find . -name *.py | grep -v setup.py | grep -v /doc/` |& tee flake8_log.txt
      - name: Upload flake8 resutls
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: flake8_artifact
          path: flake8_log.txt

