name: flake8

on:
  pull_request:
  push:

jobs:
  flake8:
    name: falke8 style checker
    runs-on: ubuntu-latest
    steps:
      - name: setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.5
          architecture: x64
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 --ignore N802,N806 `find . -name *.py | grep -v setup.py | grep -v /doc/`
        
