name: unit test

on: [push, pull_request]

env:
  CONDA_ENV: ooi

jobs:
  unit_test:
    name: ${{ matrix.python-version }}-unit-test
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        experimental: [false]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags.
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ooipy
      run: |
        python -m pip install -e .
    - name: Run unit tests
      env:
        FORCE_COLOR: 3
      run: pytest -vv tests |& tee unit_test_log${{ matrix.python-version }}.log
    - name: Upload unit test log
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: unit_test_log${{ matrix.python-version }}
        path: unit_test_log${{ matrix.python-version }}.log