# This is a basic workflow that is manually triggered

name: unit test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

jobs:
  install_conda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    #- name: Set up Python 3.8
    #  uses: actions/setup-python@v1
    #  with:
    #    python-version: 3.8
    - name: Install conda
      uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: ooi
        environment-file: conda_envs/ooi_linux.yml
        python-version: 3.5
        #condarc-file: etc/example-condarc.yml
        auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        conda list
      #uses: s-weigand/setup-conda@v1
      #with:
      #  activate-conda: false
      #  update-conda: true
      #  conda_channels: anaconda, conda-forge
    #- run: conda --version
    #- run: which python
    #- run: source .bashrc
    #- run: cd conda_envs
    #- run: conda env list
    #- name: enable conda activate
    #  run: eval "$(conda shell.bash hook)"
    #- run: conda init bash
    #- run: exec bash -l
    #- name: Activate OOI env
    #  run: conda activate ooi
    #- name: check envs
    #  if: ${{ always() }}
    #  run: conda env list 
    #- name: add conda forge
    #  run: conda config --add channels conda-forge
    #- name: create obspy env
    #  run: conda create -n obspy python=3.8
    - run: conda init fish
    - name: activate obspy
      run: conda activate obspy
    #- name: test package import
    #  run: python3
    #- run: import obspy
    - name: run unit tests
      run: py.test ooipy
   
    
