# This is a basic workflow that is manually triggered

name: unit test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

jobs:
  install_conda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install conda
      uses: s-weigand/setup-conda@v1
    - run: conda --version
    - run: which python
    - run: ls
    #- name: add conda forge
    #  run: conda config --add channels conda-forge
    #- name: create obspy env
    #  run: conda create -n obspy python=3.8
    #- run: conda init bash
    #- name: activate obspy
    #  run: conda activate obspy
    
